# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        CIRCULO ODONTOLOGICO
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, tabla.css, av.css, datePicker.css]

  javascripts:    [jquery-1.5.1.min.js, jquery-ui-1.8.13.custom.min.js, date.js, jquery.datePicker.js, jquery.dataTables.js]

  has_layout:     true
  layout:         layout
